services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\InspireCocktailDemoBundle\Controller\Studio\:
        resource: '../src/Controller/Studio'
        tags: [ 'controller.service_arguments' ]

    Pimcore\Bundle\InspireCocktailDemoBundle\EventSubscriber\CocktailIconSubscriber: ~
