services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pimcore\Bundle\InspireCocktailDemoBundle\Controller\Studio\:
        resource: '../src/Controller/Studio'
        public: true
        tags: [ 'controller.service_arguments' ]

    Pimcore\Bundle\InspireCocktailDemoBundle\EventSubscriber\CocktailIconSubscriber: ~

    # Service
    Pimcore\Bundle\InspireCocktailDemoBundle\Service\CocktailServiceInterface:
        class: Pimcore\Bundle\InspireCocktailDemoBundle\Service\CocktailService

    # Hydrator
    Pimcore\Bundle\InspireCocktailDemoBundle\Hydrator\CocktailHydratorInterface:
        class: Pimcore\Bundle\InspireCocktailDemoBundle\Hydrator\CocktailHydrator

    # Repository
    Pimcore\Bundle\InspireCocktailDemoBundle\Repository\CocktailRepositoryInterface:
        class: Pimcore\Bundle\InspireCocktailDemoBundle\Repository\CocktailRepository
