pimcore_inspire_cocktail_demo_studio:
    resource: '@PimcoreInspireCocktailDemoBundle/src/Controller/Studio'
    type: attribute
    prefix: '%pimcore_studio_backend.url_prefix%/bundle/inspire-cocktail-demo'
    options:
        expose: true
